apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-springboot-app
  template:
    metadata:
      labels:
        app: my-springboot-app
    spec:
      containers:
        - name: my-springboot-app
          image: ghcr.io/dsanchor/demo-copilot-2112-1/my-springboot-app:$IMAGE_TAG
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-springboot-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
